### ISSUE TITLE
Default styles and testing

### ISSUE THREAD

**Issue by inomn** [garronej/keycloakify-starter#2]
Hi! First of all thank you for this package. I have a few issues, maybe you can help me:

- How can i exclude default styles? Currently, default `login.css` is injected in the app
- test layout for login page in development mode looks good (npm run start), however, after building template, uploading it into my keycloak, and selecting Login theme for my Realm - nothings happens, theme is still looks default. In builder directory there are resources folder, and resources/build contains my styles, but there are also resources/css with default styles, and bg images

Thanks.

**Comment by garronej** [comment]
Hi @inomn thanks for reaching out,  

> How can i exclude default styles? Currently, default login.css is injected in the app  

https://github.com/InseeFrLab/keycloakify/blob/3c338e983ff7b8dda1339fb7aa48778a8f55449b/src/lib/components/Template.tsx#L23-L26

> test layout for login page in development mode looks good (npm run start), however, after building template, uploading it into my keycloak, and selecting Login theme for my Realm - nothings happens, theme is still looks default. In builder directory there are resources folder, and resources/build contains my styles, but there are also resources/css with default styles, and bg images   

I can't tell you anything without seeing the code. Try importing the keycloakify-starter.  

Could you please reopen this issue on the main repo?   https://github.com/InseeFrLab/keycloakify

Best regard
